name: Generar APK

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  # Permite ejecutarlo manualmente desde GitHub
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Compilar APK
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v6

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Dar permisos a Gradle Wrapper
        run: chmod +x gradlew

      - name: Compilar APK debug
        run: ./gradlew :app:assembleDebug --stacktrace

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
